### ISSUE TITLE
Eval datasets with answer

### ISSUE THREAD

**Issue by ssbuild** [FudanDISC/DISC-LawLLM#13]
Could you provide evals datasets with answerrt

**Comment by Charlie-XIAO** [comment]
We are planning to release the whole DISC-Law-Eval benchmark, including the evaluation framework and our evaluation dataset.

**Comment by ssbuild** [comment]
thank you good job.
can you release the dev dataset to huggingface,  like cevals ,  
and you own test dataset

**Comment by Charlie-XIAO** [comment]
Do you mean the training set? I believe the DISC-Law-SFT dataset is already released (please see README), except the QA part which will not be open sourced.

**Comment by ssbuild** [comment]
not training dataset , evals datasets  
cevals public dev evals datasets  ,  and they own test evals datasets to evaluate llm and ranking.
i mean you whether can do same as them.

**Comment by Charlie-XIAO** [comment]
From what I know, C-Eval releases datasets on HuggingFace with questions but no answers, and allows you to upload your results to be evaluated. Did I miss anything?

Regardless, what we will release is the evaluation dataset **with answers** and the evaluation scripts, so you do your evaluation locally instead of uploading your results to us.

**Comment by ssbuild** [comment]
I have the same legal job that urgently needs this evaluation data set, no matter how much I look forward to it

**Comment by Charlie-XIAO** [comment]
I’m so sorry but I need to follow the schedule. I promise we will release it as soon as it is done.
